# Generated by Django 3.2.4 on 2021-06-06 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210604_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demande',
            old_name='created_at',
            new_name='date',
        ),
    ]
