# Generated by Django 3.2.4 on 2021-06-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_created_at_demande_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Predicateur',
            new_name='Auteur',
        ),
        migrations.RemoveField(
            model_name='pub',
            name='Predicateurs',
        ),
        migrations.AddField(
            model_name='pub',
            name='auteurs',
            field=models.ManyToManyField(blank=True, related_name='Pubs', to='blog.Auteur'),
        ),
        migrations.AlterField(
            model_name='pub',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
