# Generated by Django 3.2.4 on 2021-06-11 09:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_ncontacte'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub',
            name='likeur',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
